using System.Text;
using System.Text.RegularExpressions;

namespace ManifestApp.Core;

/// <summary>
/// Strips upstream manifest branding from .lua files and prepends OpenSteam credit.
/// Mirrors app/lib/clean-manifest.ts on the API.
/// </summary>
public static class ManifestLuaCleaner
{
    public const string SiteUrl = "https://opensteam.lol";

    private static readonly string[] BannedFragments =
    [
        "twentytwo cloud",
        "twentytwo server",
        "redistribution of twentytwo",
        "discord.com/invite/vwgwetftxw",
        "hubcap manifest",
        "hubcapmanifest.com",
        "depotbox",
        "depotbox.org",
        "total depots:",
        "total dlcs:",
        "shared depots:",
    ];

    private static readonly Regex FuncCall =
        new(@"^(addappid|setManifestid)\s*\(", RegexOptions.IgnoreCase | RegexOptions.CultureInvariant);

    public static string BuildCredit() =>
        "-- ────────────────────────────────────────────────────────────\n" +
        "--  Generated by OpenSteam\n" +
        $"--  {SiteUrl}\n" +
        "-- ────────────────────────────────────────────────────────────\n\n";

    public static string? CleanLua(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw))
            return null;

        var cleanedLines = new List<string>();
        foreach (var line in raw.Replace("\r\n", "\n").Replace('\r', '\n').Split('\n'))
        {
            var stripped = line.Trim();
            if (stripped.Length == 0 || stripped.StartsWith("--", StringComparison.Ordinal))
                continue;

            var low = stripped.ToLowerInvariant();
            if (BannedFragments.Any(frag => low.Contains(frag, StringComparison.Ordinal)))
                continue;

            if (!FuncCall.IsMatch(stripped))
                continue;

            var cutAt = stripped.Length;
            var depth = 0;
            for (var i = 0; i < stripped.Length; i++)
            {
                if (stripped[i] == '(') depth++;
                else if (stripped[i] == ')')
                {
                    depth--;
                    if (depth == 0)
                    {
                        cutAt = i + 1;
                        break;
                    }
                }
            }

            var cleaned = stripped[..cutAt];
            cleaned = Regex.Replace(cleaned, "^addappid", "addappid", RegexOptions.IgnoreCase);
            cleaned = Regex.Replace(cleaned, "^setmanifestid", "setManifestid", RegexOptions.IgnoreCase);
            cleanedLines.Add(cleaned);
        }

        if (cleanedLines.Count == 0 || cleanedLines.All(l => !l.StartsWith("addappid(", StringComparison.OrdinalIgnoreCase)))
            return null;

        return BuildCredit() + string.Join('\n', cleanedLines) + '\n';
    }

    /// <summary>Rewrite .lua entries inside a manifest zip; returns original bytes on failure.</summary>
    public static byte[] CleanManifestZip(byte[] input)
    {
        try
        {
            using var inMs = new MemoryStream(input, writable: false);
            using var outMs = new MemoryStream();
            var changed = false;

            using (var archive = new System.IO.Compression.ZipArchive(inMs, System.IO.Compression.ZipArchiveMode.Read, leaveOpen: true))
            using (var outArchive = new System.IO.Compression.ZipArchive(outMs, System.IO.Compression.ZipArchiveMode.Create, leaveOpen: true))
            {
                foreach (var entry in archive.Entries)
                {
                    if (entry.FullName.EndsWith('/'))
                        continue;

                    using var entryStream = entry.Open();
                    using var ms = new MemoryStream();
                    entryStream.CopyTo(ms);
                    var bytes = ms.ToArray();

                    if (entry.Name.EndsWith(".lua", StringComparison.OrdinalIgnoreCase))
                    {
                        var raw = Encoding.UTF8.GetString(bytes);
                        var cleaned = CleanLua(raw);
                        if (cleaned != null &&
                            !string.Equals(raw.Replace("\r", ""), cleaned.Replace("\r", ""), StringComparison.Ordinal))
                        {
                            bytes = Encoding.UTF8.GetBytes(cleaned);
                            changed = true;
                        }
                    }

                    var outEntry = outArchive.CreateEntry(entry.FullName, System.IO.Compression.CompressionLevel.Optimal);
                    using var outStream = outEntry.Open();
                    outStream.Write(bytes, 0, bytes.Length);
                }
            }

            return changed ? outMs.ToArray() : input;
        }
        catch
        {
            return input;
        }
    }
}
